-- Run this file once in Supabase SQL Editor.
-- It is safe to run again: tables, policies and starter rows are idempotent.

create table if not exists public.cover_profiles (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.cover_runtime (
  id text primary key references public.cover_profiles(id) on delete cascade,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.cover_socials (
  id bigint generated by default as identity primary key,
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  sort_order integer not null default 0,
  label text not null,
  value text not null default '',
  href text not null default ''
);

create table if not exists public.cover_memories (
  id text primary key,
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  sort_order integer not null default 0,
  date text not null default '',
  title text not null,
  caption text not null default ''
);

create table if not exists public.cover_gallery_items (
  id text primary key,
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  sort_order integer not null default 0,
  title text not null,
  caption text not null default '',
  image_url text not null default ''
);

create table if not exists public.cover_tags (
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  value text not null,
  sort_order integer not null default 0,
  primary key (profile_id, value)
);

create table if not exists public.cover_stickers (
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  value text not null,
  sort_order integer not null default 0,
  primary key (profile_id, value)
);

create table if not exists public.cover_moods (
  id bigint generated by default as identity primary key,
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  sort_order integer not null default 0,
  label text not null,
  icon_key text not null,
  color text not null,
  quote text not null default ''
);

create table if not exists public.cover_fortunes (
  id bigint generated by default as identity primary key,
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  sort_order integer not null default 0,
  value text not null
);

create table if not exists public.cover_auras (
  id bigint generated by default as identity primary key,
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  sort_order integer not null default 0,
  value text not null
);

create table if not exists public.cover_charms (
  id text primary key,
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  sort_order integer not null default 0,
  label text not null,
  icon_key text not null
);

create table if not exists public.cover_guest_notes (
  id bigint generated by default as identity primary key,
  profile_id text not null references public.cover_profiles(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 240),
  created_at timestamptz not null default now()
);

create index if not exists cover_socials_profile_order_idx on public.cover_socials(profile_id, sort_order);
create index if not exists cover_memories_profile_order_idx on public.cover_memories(profile_id, sort_order);
create index if not exists cover_gallery_profile_order_idx on public.cover_gallery_items(profile_id, sort_order);
create index if not exists cover_moods_profile_order_idx on public.cover_moods(profile_id, sort_order);
create index if not exists cover_notes_profile_created_idx on public.cover_guest_notes(profile_id, created_at desc);

insert into public.cover_profiles (id, data)
values (
  'main',
  '{
    "name": "Nguyen Cat Tuong",
    "displayName": "Your Name",
    "username": "@yourusername",
    "role": "Dream Chaser",
    "location": "Vietnam",
    "headline": "Creating stories with style, silence, and vision.",
    "bio": "A soft chaos soul with a pink-black heart, collecting moments and turning them into tiny digital dreams.",
    "quote": "Silent progress is still progress.",
    "status": "Focused on my dream",
    "birthday": "Feb 16",
    "zodiac": "Aquarius",
    "luckyNumber": "16",
    "favoriteColor": "Hot Pink",
    "currentMood": "Dreamy",
    "aura": "Soft Rebel",
    "playlist": "Midnight Pink",
    "playlistUrl": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    "playlistDuration": "4:21",
    "dreamMeter": 88,
    "vibeScore": 99,
    "portraitUrl": "/images/profile-cutout.png",
    "avatarUrl": "",
    "accent": "pink",
    "stats": { "era": "Pink Era", "focus": "Dreams", "energy": "Soft" },
    "tags": ["Dreamer", "Focused", "Creative", "Elegant", "Y2K", "Grateful"],
    "socials": [
      { "label": "Facebook", "value": "yourusername", "href": "https://www.facebook.com/yourusername" },
      { "label": "Instagram", "value": "@yourusername", "href": "https://www.instagram.com/yourusername" },
      { "label": "TikTok", "value": "@yourusername", "href": "https://www.tiktok.com/@yourusername" }
    ],
    "memories": [
      { "id": "memory-1", "date": "13 Feb", "title": "Latest Memory", "caption": "A quiet moment, a loud dream." },
      { "id": "memory-2", "date": "16 Feb", "title": "Birthday Mood", "caption": "Still growing, still glowing." },
      { "id": "memory-3", "date": "24 Feb", "title": "Pink Night", "caption": "Offline, but still glowing." }
    ],
    "gallery": [
      { "id": "gallery-1", "title": "Mood 01", "caption": "Midnight pink.", "imageUrl": "" },
      { "id": "gallery-2", "title": "Mood 02", "caption": "Soft rebel energy.", "imageUrl": "" },
      { "id": "gallery-3", "title": "Mood 03", "caption": "Dream archive.", "imageUrl": "" }
    ],
    "stickers": ["main character", "pink mood", "soft chaos", "offline but glowing", "lucky star", "dream loading", "do not disturb", "secret era"],
    "moods": [
      { "label": "Dreamy", "iconKey": "cloud", "color": "#ff5faf", "quote": "Soft heart, loud dreams." },
      { "label": "Chaos Cute", "iconKey": "zap", "color": "#f472b6", "quote": "A little messy, still iconic." },
      { "label": "Midnight Glow", "iconKey": "moon", "color": "#e11d74", "quote": "Offline but glowing." },
      { "label": "Lucky Star", "iconKey": "star", "color": "#ff2f8f", "quote": "Today feels like a secret win." },
      { "label": "Soft Rebel", "iconKey": "heart", "color": "#fb7185", "quote": "Gentle look, strong mind." }
    ],
    "fortunes": [
      "Someone is secretly inspired by your energy.",
      "Your quiet work is about to become visible.",
      "A pink little miracle is loading...",
      "You are closer than you think.",
      "Main character moment unlocked.",
      "Today is for soft power and sharp focus."
    ],
    "auras": ["Pink Velvet", "Soft Rebel", "Midnight Rose", "Cherry Noir", "Dream Glitch"],
    "charms": [
      { "id": "heart", "iconKey": "heart", "label": "Heart" },
      { "id": "star", "iconKey": "star", "label": "Star" },
      { "id": "moon", "iconKey": "moon", "label": "Moon" },
      { "id": "gem", "iconKey": "gem", "label": "Gem" }
    ]
  }'::jsonb
)
on conflict (id) do nothing;

insert into public.cover_runtime (id, data)
values (
  'main',
  '{
    "isFollowing": false,
    "liked": false,
    "likeCount": 0,
    "vibeScore": 99,
    "luckyNumber": "16",
    "currentMood": "Dreamy",
    "aura": "Soft Rebel",
    "activeStickers": [],
    "activeCharms": [],
    "selectedStar": null,
    "guestNotes": ["your vibe is cute", "pink era unlocked"]
  }'::jsonb
)
on conflict (id) do nothing;

update public.cover_runtime
set data = jsonb_set(data, '{likeCount}', '0'::jsonb, true)
where id = 'main'
  and coalesce((data->>'liked')::boolean, false) = false
  and coalesce((data->>'likeCount')::integer, 0) = 99;

insert into public.cover_socials (profile_id, sort_order, label, value, href)
select 'main', values_table.sort_order, values_table.label, values_table.value, values_table.href
from (values
  (0, 'Facebook', 'yourusername', 'https://www.facebook.com/yourusername'),
  (1, 'Instagram', '@yourusername', 'https://www.instagram.com/yourusername'),
  (2, 'TikTok', '@yourusername', 'https://www.tiktok.com/@yourusername')
) as values_table(sort_order, label, value, href)
where not exists (select 1 from public.cover_socials where profile_id = 'main');

insert into public.cover_memories (id, profile_id, sort_order, date, title, caption)
values
  ('memory-1', 'main', 0, '13 Feb', 'Latest Memory', 'A quiet moment, a loud dream.'),
  ('memory-2', 'main', 1, '16 Feb', 'Birthday Mood', 'Still growing, still glowing.'),
  ('memory-3', 'main', 2, '24 Feb', 'Pink Night', 'Offline, but still glowing.')
on conflict (id) do nothing;

insert into public.cover_gallery_items (id, profile_id, sort_order, title, caption, image_url)
values
  ('gallery-1', 'main', 0, 'Mood 01', 'Midnight pink.', ''),
  ('gallery-2', 'main', 1, 'Mood 02', 'Soft rebel energy.', ''),
  ('gallery-3', 'main', 2, 'Mood 03', 'Dream archive.', '')
on conflict (id) do nothing;

insert into public.cover_tags (profile_id, value, sort_order)
values
  ('main', 'Dreamer', 0), ('main', 'Focused', 1), ('main', 'Creative', 2),
  ('main', 'Elegant', 3), ('main', 'Y2K', 4), ('main', 'Grateful', 5)
on conflict (profile_id, value) do nothing;

insert into public.cover_stickers (profile_id, value, sort_order)
values
  ('main', 'main character', 0), ('main', 'pink mood', 1), ('main', 'soft chaos', 2),
  ('main', 'offline but glowing', 3), ('main', 'lucky star', 4), ('main', 'dream loading', 5),
  ('main', 'do not disturb', 6), ('main', 'secret era', 7)
on conflict (profile_id, value) do nothing;

insert into public.cover_moods (profile_id, sort_order, label, icon_key, color, quote)
select 'main', values_table.sort_order, values_table.label, values_table.icon_key, values_table.color, values_table.quote
from (values
  (0, 'Dreamy', 'cloud', '#ff5faf', 'Soft heart, loud dreams.'),
  (1, 'Chaos Cute', 'zap', '#f472b6', 'A little messy, still iconic.'),
  (2, 'Midnight Glow', 'moon', '#e11d74', 'Offline but glowing.'),
  (3, 'Lucky Star', 'star', '#ff2f8f', 'Today feels like a secret win.'),
  (4, 'Soft Rebel', 'heart', '#fb7185', 'Gentle look, strong mind.')
) as values_table(sort_order, label, icon_key, color, quote)
where not exists (select 1 from public.cover_moods where profile_id = 'main');

update public.cover_moods
set color = case label
  when 'Dreamy' then '#ff5faf'
  when 'Chaos Cute' then '#f472b6'
  when 'Midnight Glow' then '#e11d74'
  when 'Lucky Star' then '#ff2f8f'
  when 'Soft Rebel' then '#fb7185'
  else color
end
where profile_id = 'main'
  and label in ('Dreamy', 'Chaos Cute', 'Midnight Glow', 'Lucky Star', 'Soft Rebel');

insert into public.cover_fortunes (profile_id, sort_order, value)
select 'main', values_table.sort_order, values_table.value
from (values
  (0, 'Someone is secretly inspired by your energy.'),
  (1, 'Your quiet work is about to become visible.'),
  (2, 'A pink little miracle is loading...'),
  (3, 'You are closer than you think.'),
  (4, 'Main character moment unlocked.'),
  (5, 'Today is for soft power and sharp focus.')
) as values_table(sort_order, value)
where not exists (select 1 from public.cover_fortunes where profile_id = 'main');

insert into public.cover_auras (profile_id, sort_order, value)
select 'main', values_table.sort_order, values_table.value
from (values
  (0, 'Pink Velvet'), (1, 'Soft Rebel'), (2, 'Midnight Rose'),
  (3, 'Cherry Noir'), (4, 'Dream Glitch')
) as values_table(sort_order, value)
where not exists (select 1 from public.cover_auras where profile_id = 'main');

insert into public.cover_charms (id, profile_id, sort_order, label, icon_key)
values
  ('heart', 'main', 0, 'Heart', 'heart'),
  ('star', 'main', 1, 'Star', 'star'),
  ('moon', 'main', 2, 'Moon', 'moon'),
  ('gem', 'main', 3, 'Gem', 'gem')
on conflict (id) do nothing;

insert into public.cover_guest_notes (profile_id, message)
select 'main', values_table.message
from (values ('your vibe is cute'), ('pink era unlocked')) as values_table(message)
where not exists (select 1 from public.cover_guest_notes where profile_id = 'main');

alter table public.cover_profiles enable row level security;
alter table public.cover_runtime enable row level security;
alter table public.cover_socials enable row level security;
alter table public.cover_memories enable row level security;
alter table public.cover_gallery_items enable row level security;
alter table public.cover_tags enable row level security;
alter table public.cover_stickers enable row level security;
alter table public.cover_moods enable row level security;
alter table public.cover_fortunes enable row level security;
alter table public.cover_auras enable row level security;
alter table public.cover_charms enable row level security;
alter table public.cover_guest_notes enable row level security;

drop policy if exists "Public cover profile read" on public.cover_profiles;
drop policy if exists "Public cover profile insert" on public.cover_profiles;
drop policy if exists "Public cover profile update" on public.cover_profiles;
drop policy if exists "Public cover runtime read" on public.cover_runtime;
drop policy if exists "Public cover runtime insert" on public.cover_runtime;
drop policy if exists "Public cover runtime update" on public.cover_runtime;

drop policy if exists "Demo public profile access" on public.cover_profiles;
create policy "Demo public profile access" on public.cover_profiles for all to anon using (true) with check (id = 'main');

drop policy if exists "Demo public runtime access" on public.cover_runtime;
create policy "Demo public runtime access" on public.cover_runtime for all to anon using (true) with check (id = 'main');

drop policy if exists "Demo public socials access" on public.cover_socials;
create policy "Demo public socials access" on public.cover_socials for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public memories access" on public.cover_memories;
create policy "Demo public memories access" on public.cover_memories for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public gallery access" on public.cover_gallery_items;
create policy "Demo public gallery access" on public.cover_gallery_items for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public tags access" on public.cover_tags;
create policy "Demo public tags access" on public.cover_tags for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public stickers access" on public.cover_stickers;
create policy "Demo public stickers access" on public.cover_stickers for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public moods access" on public.cover_moods;
create policy "Demo public moods access" on public.cover_moods for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public fortunes access" on public.cover_fortunes;
create policy "Demo public fortunes access" on public.cover_fortunes for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public auras access" on public.cover_auras;
create policy "Demo public auras access" on public.cover_auras for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public charms access" on public.cover_charms;
create policy "Demo public charms access" on public.cover_charms for all to anon using (true) with check (profile_id = 'main');

drop policy if exists "Demo public notes access" on public.cover_guest_notes;
create policy "Demo public notes access" on public.cover_guest_notes for all to anon using (true) with check (profile_id = 'main');

insert into storage.buckets (id, name, public)
values ('cover-images', 'cover-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Demo public cover image read" on storage.objects;
create policy "Demo public cover image read"
on storage.objects for select
to anon
using (bucket_id = 'cover-images');

drop policy if exists "Demo public cover image upload" on storage.objects;
create policy "Demo public cover image upload"
on storage.objects for insert
to anon
with check (bucket_id = 'cover-images');

drop policy if exists "Demo public cover image update" on storage.objects;
create policy "Demo public cover image update"
on storage.objects for update
to anon
using (bucket_id = 'cover-images')
with check (bucket_id = 'cover-images');

drop policy if exists "Demo public cover image delete" on storage.objects;
create policy "Demo public cover image delete"
on storage.objects for delete
to anon
using (bucket_id = 'cover-images');
